export const config = {
  EMAIL_SERVICE_ID: process.env.REACT_APP_EMAIL_SERVICE_ID,
  EMAIL_TEMPLATE_ID: process.env.REACT_APP_EMAIL_TEMPLATE_ID,
  EMAIL_PUBLIC_KEY: process.env.REACT_APP_EMAIL_PUBLIC_KEY,
};
